[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "cd src && daphne msakin.asgi:application --port $PORT --bind 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[env]
PYTHON_VERSION = "3.11.7"
