[build]
builder = "nixpacks"
buildCommand = "cd src && pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "cd src && python manage.py migrate && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p $PORT msakin.asgi:application"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicy = "always"

[env]
PYTHON_VERSION = "3.11.7"
NIXPACKS_PYTHON_VERSION = "3.11.7"
DATABASE_URL = "postgresql://"
