# Generated by Django 5.1.4 on 2024-12-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertycomment_parent_commentlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
