# Generated by Django 5.1.4 on 2024-12-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyrequest_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequest',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='properties.property'),
        ),
    ]
