# Generated by Django 5.1.4 on 2024-12-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyrequest_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequest',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'للبيع'), ('rent', 'للإيجار')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='preferred_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('land', 'أرض'), ('commercial', 'تجاري')], max_length=20),
        ),
    ]
